title: Joshua Vera O'Steen
logo: ./assets/img/joshmemoji.png
description: Skilled Researcher, Future Data Scientist, Student of Statistics and Political Science
location:        –– Washington, D.C. ––
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
