title: Joshua Vera O'Steen
logo: ./assets/img/Chirasree_m.png
description: Skilled Researcher, Future Data Scientist, Student of Statistics and Political Science
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
